spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    initialization-mode: always
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:test # In-Memory mode
    username: sa
    password:
#  sql:
#    init:
#      mode: always
#      data-locations: classpath:/data.sql

  jpa:
    hibernate:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.Mysql8Dialect
    defer-datasource-initialization: true
    sql:
      init:
        mode: always
    open-in-view: false
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        ddl-auto: create-drop